pipeline {
    agent any

    // ── Tool versions configured in Manage Jenkins → Global Tool Configuration ──
    tools {
        maven 'My Maven'   // name you gave Maven in Jenkins Global Tools
        jdk   'My Java'    // name you gave the JDK in Jenkins Global Tools
    }

    // ── All Stripe secrets live in Jenkins Credentials Store ──────────────────
    //   Kind          : Secret text
    //   IDs used below: STRIPE_AUTH_KEY, STRIPE_MERCHANT_ACCOUNT_ID
    //   (baseURI and amount have sensible defaults in BaseClass; add them here
    //    only if you ever need to override them per-environment)
    environment {
        STRIPE_BASE_URI            = 'https://api.stripe.com'
        STRIPE_AMOUNT              = '2000'
        // Secrets are bound from Jenkins Credentials – never hard-coded
        STRIPE_AUTH_KEY            = credentials('STRIPE_AUTH_KEY')
        STRIPE_MERCHANT_ACCOUNT_ID = credentials('STRIPE_MERCHANT_ACCOUNT_ID')
        VERIFIED_EMAIL             ='devil.burdwan@gmail.com'
    }

    parameters {
        // Let the person triggering the build choose which suite to run.
        // Defaults to the full regression suite.
        choice(
            name: 'SUITE',
            choices: [
                'testng.xml',
                'testng-regression.xml',
                'testng-smoke.xml',
                'testng-e2e.xml',
                'testng-marketplace-e2e.xml',
                'testng-subscription-e2e.xml',
                'testng-saved-card-e2e.xml',
                'testng-disputes-e2e.xml',
                'testng-idempotency.xml',
                'testng-negative.xml',
                'testng-flow.xml',
                'testng-auth.xml'
            ],
            description: 'TestNG suite XML file to execute'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                // Jenkins SCM checkout – no credentials needed here because
                // config.properties is gitignored; only source code is pulled.
                checkout scm
                echo "✅ Source checked out. Suite selected: ${params.SUITE}"
            }
        }

        stage('Build & Test') {
            steps {
                    bat "mvn clean test -Dsurefire.suiteXmlFiles=%SUITE% --no-transfer-progress"
                }
            post {
                    always {
                        testNG reportFilenamePattern: '**/target/surefire-reports/testng-results.xml'
                    }
                }
        }

        stage('Publish Extent Report') {
            steps {
                // Publish the timestamped HTML report generated by ExtentReportListener
                publishHTML(target: [
                    allowMissing         : true,
                    alwaysLinkToLastBuild: true,
                    keepAll              : true,
                    reportDir            : 'reports',
                    reportFiles          : 'ExtentReport.html',
                    reportName           : 'Extent Test Report'
                ])
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive logs and the zip archives of older reports
                archiveArtifacts artifacts: 'target/logs/**/*.log, reports/archive/*.zip',
                                 allowEmptyArchive: true
            }
        }
    }

    post {
        success {
            echo '✅ All tests passed.'
        }
        failure {
            echo '❌ Build or tests failed. Check the Extent Report and console output.'
        }
        always {
            // Clean workspace after run to avoid stale artifacts affecting the next build
            cleanWs()
        }
    }
}
